spring.application.name=baseclick_bd

spring.datasource.url=jdbc:mysql://localhost:3306/baseclick_bd
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true